name: "CI - Trigger build and push"
on:
  push:
    branches: [master]
    paths:
      - ./**
      - .github/workflows/ci_prod.yml
  pull_request:
    branches: [master]
    paths:
      - ./**
      - .github/workflows/ci_prod.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: TIHLDE/tihlde-workflows/.github/workflows/_ci_ghcr.yml
    with:
      context: .
      dockerfile: ./Dockerfile

  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    uses: TIHLDE/tihlde-workflows/.github/workflows/_notify_deploy.yml
